[package]
name = "grid-bot"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
poise = "0.5"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
vaultrs = "0.7"
