//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace Grid.Client
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://roblox.com/", ConfigurationName="Grid.Client.GridServerServiceSoap")]
    public interface GridServerServiceSoap : System.IDisposable
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.Status GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.Status> GetStatusAsync();
        
        // CODEGEN: Parameter 'OpenJobResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/OpenJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.OpenJobResponse OpenJob(Grid.Client.OpenJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/OpenJob", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.OpenJobResponse> OpenJobAsync(Grid.Client.OpenJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/OpenJobEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.LuaValue[] OpenJobEx(Grid.Client.Job job, Grid.Client.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/OpenJobEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.LuaValue[]> OpenJobExAsync(Grid.Client.Job job, Grid.Client.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/RenewLease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        double RenewLease(string jobID, double expirationInSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/RenewLease", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RenewLeaseAsync(string jobID, double expirationInSeconds);
        
        // CODEGEN: Parameter 'ExecuteResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.ExecuteResponse Execute(Grid.Client.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.ExecuteResponse> ExecuteAsync(Grid.Client.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/ExecuteEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.LuaValue[] ExecuteEx(string jobID, Grid.Client.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/ExecuteEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.LuaValue[]> ExecuteExAsync(string jobID, Grid.Client.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CloseJob(string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseJob", ReplyAction="*")]
        System.Threading.Tasks.Task CloseJobAsync(string jobID);
        
        // CODEGEN: Parameter 'BatchJobResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/BatchJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.BatchJobResponse BatchJob(Grid.Client.BatchJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/BatchJob", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.BatchJobResponse> BatchJobAsync(Grid.Client.BatchJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/BatchJobEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.LuaValue[] BatchJobEx(Grid.Client.Job job, Grid.Client.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/BatchJobEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.LuaValue[]> BatchJobExAsync(Grid.Client.Job job, Grid.Client.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetExpiration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        double GetExpiration(string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetExpiration", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetExpirationAsync(string jobID);
        
        // CODEGEN: Parameter 'GetAllJobsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetAllJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.GetAllJobsResponse GetAllJobs(Grid.Client.GetAllJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetAllJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.GetAllJobsResponse> GetAllJobsAsync(Grid.Client.GetAllJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetAllJobsEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.Job[] GetAllJobsEx();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetAllJobsEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.Job[]> GetAllJobsExAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseExpiredJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int CloseExpiredJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseExpiredJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CloseExpiredJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseAllJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int CloseAllJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseAllJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CloseAllJobsAsync();
        
        // CODEGEN: Parameter 'DiagResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/Diag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.DiagResponse Diag(Grid.Client.DiagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/Diag", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.DiagResponse> DiagAsync(Grid.Client.DiagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/DiagEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Grid.Client.LuaValue[] DiagEx(int type, string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/DiagEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Grid.Client.LuaValue[]> DiagExAsync(int type, string jobID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string versionField;
        
        private int environmentCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int environmentCount
        {
            get
            {
                return this.environmentCountField;
            }
            set
            {
                this.environmentCountField = value;
                this.RaisePropertyChanged("environmentCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public partial class LuaValue : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private LuaType typeField;
        
        private string valueField;
        
        private LuaValue[] tableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LuaType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LuaValue[] table
        {
            get
            {
                return this.tableField;
            }
            set
            {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public enum LuaType
    {
        
        /// <remarks/>
        LUA_TNIL,
        
        /// <remarks/>
        LUA_TBOOLEAN,
        
        /// <remarks/>
        LUA_TNUMBER,
        
        /// <remarks/>
        LUA_TSTRING,
        
        /// <remarks/>
        LUA_TTABLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public partial class ScriptExecution : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string nameField;
        
        private string scriptField;
        
        private LuaValue[] argumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string script
        {
            get
            {
                return this.scriptField;
            }
            set
            {
                this.scriptField = value;
                this.RaisePropertyChanged("script");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LuaValue[] arguments
        {
            get
            {
                return this.argumentsField;
            }
            set
            {
                this.argumentsField = value;
                this.RaisePropertyChanged("arguments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public partial class Job : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string idField;
        
        private double expirationInSecondsField;
        
        private int categoryField;
        
        private double coresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double expirationInSeconds
        {
            get
            {
                return this.expirationInSecondsField;
            }
            set
            {
                this.expirationInSecondsField = value;
                this.RaisePropertyChanged("expirationInSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double cores
        {
            get
            {
                return this.coresField;
            }
            set
            {
                this.coresField = value;
                this.RaisePropertyChanged("cores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenJob", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class OpenJobRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        public Grid.Client.Job job;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=1)]
        public Grid.Client.ScriptExecution script;
        
        public OpenJobRequest()
        {
        }
        
        public OpenJobRequest(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            this.job = job;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenJobResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class OpenJobResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OpenJobResult")]
        public Grid.Client.LuaValue[] OpenJobResult;
        
        public OpenJobResponse()
        {
        }
        
        public OpenJobResponse(Grid.Client.LuaValue[] OpenJobResult)
        {
            this.OpenJobResult = OpenJobResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Execute", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        public string jobID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=1)]
        public Grid.Client.ScriptExecution script;
        
        public ExecuteRequest()
        {
        }
        
        public ExecuteRequest(string jobID, Grid.Client.ScriptExecution script)
        {
            this.jobID = jobID;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class ExecuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExecuteResult", IsNullable=true)]
        public Grid.Client.LuaValue[] ExecuteResult;
        
        public ExecuteResponse()
        {
        }
        
        public ExecuteResponse(Grid.Client.LuaValue[] ExecuteResult)
        {
            this.ExecuteResult = ExecuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchJob", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class BatchJobRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        public Grid.Client.Job job;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=1)]
        public Grid.Client.ScriptExecution script;
        
        public BatchJobRequest()
        {
        }
        
        public BatchJobRequest(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            this.job = job;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchJobResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class BatchJobResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BatchJobResult", IsNullable=true)]
        public Grid.Client.LuaValue[] BatchJobResult;
        
        public BatchJobResponse()
        {
        }
        
        public BatchJobResponse(Grid.Client.LuaValue[] BatchJobResult)
        {
            this.BatchJobResult = BatchJobResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllJobs", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class GetAllJobsRequest
    {
        
        public GetAllJobsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllJobsResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class GetAllJobsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetAllJobsResult", IsNullable=true)]
        public Grid.Client.Job[] GetAllJobsResult;
        
        public GetAllJobsResponse()
        {
        }
        
        public GetAllJobsResponse(Grid.Client.Job[] GetAllJobsResult)
        {
            this.GetAllJobsResult = GetAllJobsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Diag", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class DiagRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=1)]
        public string jobID;
        
        public DiagRequest()
        {
        }
        
        public DiagRequest(int type, string jobID)
        {
            this.type = type;
            this.jobID = jobID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DiagResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class DiagResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DiagResult", IsNullable=true)]
        public Grid.Client.LuaValue[] DiagResult;
        
        public DiagResponse()
        {
        }
        
        public DiagResponse(Grid.Client.LuaValue[] DiagResult)
        {
            this.DiagResult = DiagResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GridServerServiceSoapChannel : Grid.Client.GridServerServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GridServerServiceSoapClient : System.ServiceModel.ClientBase<Grid.Client.GridServerServiceSoap>, Grid.Client.GridServerServiceSoap
    {
        
        public GridServerServiceSoapClient()
        {
        }
        
        public GridServerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public GridServerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GridServerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GridServerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string HelloWorld()
        {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }
        
        public string GetVersion()
        {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync()
        {
            return base.Channel.GetVersionAsync();
        }
        
        public Grid.Client.Status GetStatus()
        {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<Grid.Client.Status> GetStatusAsync()
        {
            return base.Channel.GetStatusAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Grid.Client.OpenJobResponse Grid.Client.GridServerServiceSoap.OpenJob(Grid.Client.OpenJobRequest request)
        {
            return base.Channel.OpenJob(request);
        }
        
        public Grid.Client.LuaValue[] OpenJob(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            Grid.Client.OpenJobRequest inValue = new Grid.Client.OpenJobRequest();
            inValue.job = job;
            inValue.script = script;
            Grid.Client.OpenJobResponse retVal = ((Grid.Client.GridServerServiceSoap)(this)).OpenJob(inValue);
            return retVal.OpenJobResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Grid.Client.OpenJobResponse> Grid.Client.GridServerServiceSoap.OpenJobAsync(Grid.Client.OpenJobRequest request)
        {
            return base.Channel.OpenJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<Grid.Client.OpenJobResponse> OpenJobAsync(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            Grid.Client.OpenJobRequest inValue = new Grid.Client.OpenJobRequest();
            inValue.job = job;
            inValue.script = script;
            return ((Grid.Client.GridServerServiceSoap)(this)).OpenJobAsync(inValue);
        }
        
        public Grid.Client.LuaValue[] OpenJobEx(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            return base.Channel.OpenJobEx(job, script);
        }
        
        public System.Threading.Tasks.Task<Grid.Client.LuaValue[]> OpenJobExAsync(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            return base.Channel.OpenJobExAsync(job, script);
        }
        
        public double RenewLease(string jobID, double expirationInSeconds)
        {
            return base.Channel.RenewLease(jobID, expirationInSeconds);
        }
        
        public System.Threading.Tasks.Task<double> RenewLeaseAsync(string jobID, double expirationInSeconds)
        {
            return base.Channel.RenewLeaseAsync(jobID, expirationInSeconds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Grid.Client.ExecuteResponse Grid.Client.GridServerServiceSoap.Execute(Grid.Client.ExecuteRequest request)
        {
            return base.Channel.Execute(request);
        }
        
        public Grid.Client.LuaValue[] Execute(string jobID, Grid.Client.ScriptExecution script)
        {
            Grid.Client.ExecuteRequest inValue = new Grid.Client.ExecuteRequest();
            inValue.jobID = jobID;
            inValue.script = script;
            Grid.Client.ExecuteResponse retVal = ((Grid.Client.GridServerServiceSoap)(this)).Execute(inValue);
            return retVal.ExecuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Grid.Client.ExecuteResponse> Grid.Client.GridServerServiceSoap.ExecuteAsync(Grid.Client.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Grid.Client.ExecuteResponse> ExecuteAsync(string jobID, Grid.Client.ScriptExecution script)
        {
            Grid.Client.ExecuteRequest inValue = new Grid.Client.ExecuteRequest();
            inValue.jobID = jobID;
            inValue.script = script;
            return ((Grid.Client.GridServerServiceSoap)(this)).ExecuteAsync(inValue);
        }
        
        public Grid.Client.LuaValue[] ExecuteEx(string jobID, Grid.Client.ScriptExecution script)
        {
            return base.Channel.ExecuteEx(jobID, script);
        }
        
        public System.Threading.Tasks.Task<Grid.Client.LuaValue[]> ExecuteExAsync(string jobID, Grid.Client.ScriptExecution script)
        {
            return base.Channel.ExecuteExAsync(jobID, script);
        }
        
        public void CloseJob(string jobID)
        {
            base.Channel.CloseJob(jobID);
        }
        
        public System.Threading.Tasks.Task CloseJobAsync(string jobID)
        {
            return base.Channel.CloseJobAsync(jobID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Grid.Client.BatchJobResponse Grid.Client.GridServerServiceSoap.BatchJob(Grid.Client.BatchJobRequest request)
        {
            return base.Channel.BatchJob(request);
        }
        
        public Grid.Client.LuaValue[] BatchJob(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            Grid.Client.BatchJobRequest inValue = new Grid.Client.BatchJobRequest();
            inValue.job = job;
            inValue.script = script;
            Grid.Client.BatchJobResponse retVal = ((Grid.Client.GridServerServiceSoap)(this)).BatchJob(inValue);
            return retVal.BatchJobResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Grid.Client.BatchJobResponse> Grid.Client.GridServerServiceSoap.BatchJobAsync(Grid.Client.BatchJobRequest request)
        {
            return base.Channel.BatchJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<Grid.Client.BatchJobResponse> BatchJobAsync(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            Grid.Client.BatchJobRequest inValue = new Grid.Client.BatchJobRequest();
            inValue.job = job;
            inValue.script = script;
            return ((Grid.Client.GridServerServiceSoap)(this)).BatchJobAsync(inValue);
        }
        
        public Grid.Client.LuaValue[] BatchJobEx(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            return base.Channel.BatchJobEx(job, script);
        }
        
        public System.Threading.Tasks.Task<Grid.Client.LuaValue[]> BatchJobExAsync(Grid.Client.Job job, Grid.Client.ScriptExecution script)
        {
            return base.Channel.BatchJobExAsync(job, script);
        }
        
        public double GetExpiration(string jobID)
        {
            return base.Channel.GetExpiration(jobID);
        }
        
        public System.Threading.Tasks.Task<double> GetExpirationAsync(string jobID)
        {
            return base.Channel.GetExpirationAsync(jobID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Grid.Client.GetAllJobsResponse Grid.Client.GridServerServiceSoap.GetAllJobs(Grid.Client.GetAllJobsRequest request)
        {
            return base.Channel.GetAllJobs(request);
        }
        
        public Grid.Client.Job[] GetAllJobs()
        {
            Grid.Client.GetAllJobsRequest inValue = new Grid.Client.GetAllJobsRequest();
            Grid.Client.GetAllJobsResponse retVal = ((Grid.Client.GridServerServiceSoap)(this)).GetAllJobs(inValue);
            return retVal.GetAllJobsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Grid.Client.GetAllJobsResponse> Grid.Client.GridServerServiceSoap.GetAllJobsAsync(Grid.Client.GetAllJobsRequest request)
        {
            return base.Channel.GetAllJobsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Grid.Client.GetAllJobsResponse> GetAllJobsAsync()
        {
            Grid.Client.GetAllJobsRequest inValue = new Grid.Client.GetAllJobsRequest();
            return ((Grid.Client.GridServerServiceSoap)(this)).GetAllJobsAsync(inValue);
        }
        
        public Grid.Client.Job[] GetAllJobsEx()
        {
            return base.Channel.GetAllJobsEx();
        }
        
        public System.Threading.Tasks.Task<Grid.Client.Job[]> GetAllJobsExAsync()
        {
            return base.Channel.GetAllJobsExAsync();
        }
        
        public int CloseExpiredJobs()
        {
            return base.Channel.CloseExpiredJobs();
        }
        
        public System.Threading.Tasks.Task<int> CloseExpiredJobsAsync()
        {
            return base.Channel.CloseExpiredJobsAsync();
        }
        
        public int CloseAllJobs()
        {
            return base.Channel.CloseAllJobs();
        }
        
        public System.Threading.Tasks.Task<int> CloseAllJobsAsync()
        {
            return base.Channel.CloseAllJobsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Grid.Client.DiagResponse Grid.Client.GridServerServiceSoap.Diag(Grid.Client.DiagRequest request)
        {
            return base.Channel.Diag(request);
        }
        
        public Grid.Client.LuaValue[] Diag(int type, string jobID)
        {
            Grid.Client.DiagRequest inValue = new Grid.Client.DiagRequest();
            inValue.type = type;
            inValue.jobID = jobID;
            Grid.Client.DiagResponse retVal = ((Grid.Client.GridServerServiceSoap)(this)).Diag(inValue);
            return retVal.DiagResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Grid.Client.DiagResponse> Grid.Client.GridServerServiceSoap.DiagAsync(Grid.Client.DiagRequest request)
        {
            return base.Channel.DiagAsync(request);
        }
        
        public System.Threading.Tasks.Task<Grid.Client.DiagResponse> DiagAsync(int type, string jobID)
        {
            Grid.Client.DiagRequest inValue = new Grid.Client.DiagRequest();
            inValue.type = type;
            inValue.jobID = jobID;
            return ((Grid.Client.GridServerServiceSoap)(this)).DiagAsync(inValue);
        }
        
        public Grid.Client.LuaValue[] DiagEx(int type, string jobID)
        {
            return base.Channel.DiagEx(type, jobID);
        }
        
        public System.Threading.Tasks.Task<Grid.Client.LuaValue[]> DiagExAsync(int type, string jobID)
        {
            return base.Channel.DiagExAsync(type, jobID);
        }
    }
}
