<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Shared library for commands used by grid-bot registered dynamically.</Description>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);WE_LOVE_EM_SLASH_COMMANDS</DefineConstants>
  </PropertyGroup>

  <ItemGroup Label="GridBotPackages">
    <ProjectReference Include="../utility/Shared.Utility.csproj" />
  </ItemGroup>

  <ItemGroup Label="CustomPackages">
    <ProjectReference Include="$(RootDirectory)lib/file-system/file-system/FileSystem.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/floodcheckers/core/FloodCheckers.Core.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/floodcheckers/redis/FloodCheckers.Redis.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/text/text/Text.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/networking/networking/Networking.csproj" />
  </ItemGroup>

  <ItemGroup Label="NuGetPackages">
    <PackageReference Include="Discord.Net.WebSocket" Version="3.17.4" />
    <PackageReference Include="Discord.Net.Commands" Version="3.17.4" />
    <PackageReference Include="Discord.Net.Interactions" Version="3.17.4" />
    <PackageReference Include="Loretta.CodeAnalysis.Lua" Version="0.2.11" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.12.0-dev" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Polly" Version="7.2.4" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.9.0" />
  </ItemGroup>

</Project>
