name: Security Vulnerabilty Report
description: File a security vulnerability report, use this if you have discovered a security vulnerability and wish the internal team to investigate.
title: "[Vulnerability]: "
labels: ["kind: hotfix", "priority: key deliverable", "status: backlogged", "status: needs-review"]
assignees: ["nikita-petko"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this security vulnerability report! This will be marked with the label "key deliverable", which will email @mfdlabs/sec-ops, @mfdlabs/ops and @mfdlabs/grid-team
  - type: checkboxes
    attributes:
      label: Check if there is an existing issue or pull request.
      description: Please check the [issues](https://github.com/mfdlabs/grid-bot/issues) to determine if your vulnerability has already been filed.
      options:
      - label: "I double checked issues and couldn't find any duplicates."
        required: true
  - type: checkboxes
    attributes:
      label: This occurs on the latest version of the bot.
      description: If this bug occurs on the latest version of the bot, please check this box. There will be a version string in the README.md that will correlate to a version that you can check on the bot.
      options:
      - label: I verified that this occurs on the latest version.
        required: true
  - type: checkboxes
    attributes:
      label: Have you read the Security Vulnerability Guidelines?
      description: If you have read the [Security Vulnerability Guidelines](https://github.com/mfdlabs/grid-bot/blob/master/SECURITY.md), and this issue conforms to them, please check this box.
      options:
      - label: I have read the Security Vulnerability Guidelines.
        required: true
  - type: dropdown
    id: severity
    attributes:
      label: Vulernability Severity
      description: This refers to the severity of the vulnerability. This is required.
      options:
        - "Critical"
        - "High"
        - "Medium"
        - "Low"
        - "Invonvenience"
    validations:
      required: true
  - type: textarea
    id: description
    attributes: 
      label: Description
      description: A brief explination of the vulnerability.
      placeholder: ex. Public IP address is exposed.
    validations:
      required: true
  - type: input
    id: deployment-id
    attributes:
      label: The deployment ID of the bot.
      description: This refers to the deployment ID of the bot, there will be a command that lets you retrieve this value (/support). Use this if it's version specific.
      placeholder: ex. 2022.03.06-01.36.27_master_561a09f-net48-Release
    validations:
      required: false
  - type: input
    id: dates-of-occurrence
    attributes:
      label: The dates of occurrence of the vulnerability.
      description: This refers to the dates of occurrence of the vulnerability. These can be on any time zone, but must include the year, month, day, hour, minute, and second (if possible). This accepts multiple dates, separated by commas.
      placeholder: ex. 2022/03/06 01:36:27 UTC+1, 2022/03/06 01:37:28 UTC+1, 2022/03/06 01:38:11 UTC+1
    validations:
      required: false
  - type: input
    id: machine-id
    attributes:
      label: The hostname, Machine ID and IP of the machine
      description: This refers to the hostname, Machine ID and IP of the machine, there will be a command that lets you retrieve this value (/support). This is optional, but is very helpful for debugging.
      placeholder: ex. dapp181-dec.distrubuted.jfk01-us-east-01.mfdlabs.local, JFK01-DApp181, 10.128.29.28
    validations:
      required: false
  - type: textarea
    id: images
    attributes: 
      label: Images
      description: Attach images to the vulnerability report. This is optional, but is very helpful for debugging.
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide steps to reproduce the bug. This is optional, but is highly recommended.
      placeholder: >
        1. Execute command /execute script script:BLAH BLAH
        2. Paste this code in blah blah.
        3. Magic!!
    validations:
      required: false
