<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Eval runner executable for the MFDLABS grid-bot.</Description>
  </PropertyGroup> 

  <PropertyGroup>
    <NoWarn>$(NoWarn);4014</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>

    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
  </PropertyGroup>
  
  <ItemGroup Label="GridBotPackages">
    <ProjectReference Include="../utility/Shared.Utility.csproj" />
    <ProjectReference Include="../settings/Shared.Settings.csproj" />
  </ItemGroup>

  <ItemGroup Label="NuGetPackages">
    <PackageReference Include="Discord.Net.Rest" Version="3.17.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.6.0" />
  </ItemGroup>

</Project>
