component: grid-bot

build:
  project_file: src/Grid.Bot.csproj
  component_directory: ./.deploy

  additional_args:
    - -p:IMAGE_TAG=${{ env.NOMAD_VERSION }}
    - -p:CI=true

  docker:
    docker_file: Dockerfile
    image_name: mfdlabs/grid-bot
    
deployment:
  count: 1
  namespace: grid-bot

  job: grid-bot-${{ env.NOMAD_SHORT_ENVIRONMENT }}
  
  # Passed to the meta section in Nomad
  meta:
    ENVIRONMENT: ${{ env.NOMAD_ENVIRONMENT }}
    VERSION: ${{ env.NOMAD_VERSION }}

  constraints:
    - attribute: "${meta.deployment.capabilities}"
      operator: "set_contains"
      value: "grid-bot"

  containers: # Maps to the groups section in Nomad
    - image: mfdlabs/grid-bot
      resources:
        cpu: ${{ env.NOMAD_CPU }}
        ram: ${{ env.NOMAD_RAM }}
      network:
        mode: host
        ports:
          metrics: {}
          grpc: {}
          http: {}
      services:
        - name: ${{ env.NOMAD_ENVIRONMENT }}-grid-bot
          port: metrics
          tags:
            - ${{ env.NOMAD_ENVIRONMENT }}
            - prometheus # For prometheus collector
          checks:
            - type: tcp

        - name: ${{ env.NOMAD_ENVIRONMENT }}-grid-bot
          port: http
          tags:
            - ${{ env.NOMAD_ENVIRONMENT }}
            - "traefik.enable=true"
            - "traefik.http.routers.${{ env.NOMAD_ENVIRONMENT }}-grid-bot-web.rule=(Host(`clientsettingscdn.sitetest4.robloxlabs.com`) || Host(`versioncompatibility.api.sitetest4.robloxlabs.com`) || Host(`avatar.sitetest4.robloxlabs.com`))"
            - "traefik.http.routers.${{ env.NOMAD_ENVIRONMENT }}-grid-bot-web.entrypoints=http,https"

      volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/tmp/.X11-unix:/tmp/.X11-unix'

        - '/_/_data/grid-bot/scripts:/_/_data/grid-bot/scripts'
        - '/_/_data/grid-bot/logs:/tmp/mfdlabs/logs'
        - '/_/_data/grid-bot/rcc-logs:/_/_data/grid-bot/rcc-logs'
      config_maps:
        - destination: secrets/file.env
          env: true
          on_change: restart
          data: |
            MetricsBindAddress="http://{{ env "NOMAD_IP_metrics" }}:{{ env "NOMAD_PORT_metrics" }}"
            WebServerBindAddress="http://{{ env "NOMAD_IP_http" }}:{{ env "NOMAD_PORT_http" }}"
            GridBotGrpcServerEndpoint="http://{{ env "NOMAD_IP_grpc" }}:{{ env "NOMAD_PORT_grpc" }}"

            DISPLAY=:1
            DEFAULT_LOG_LEVEL=Information
            VAULT_ADDR="${{ env.VAULT_ADDR }}"
            VAULT_TOKEN="${{ env.VAULT_TOKEN }}"
