<Project>
  <PropertyGroup Label="DefaultWarnings">
    <NoWarn>$(NoWarn);4014</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="LibStandard">
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <Import Project="$(RootDirectory)targets/git-metadata.targets" Condition="Exists('$(RootDirectory)targets/git-metadata.targets')" />

  <PropertyGroup Label="PackageMetadata">
    <Company>MFDLABS</Company>
    <Copyright>Copyright © $(Company) $([System.DateTime]::Now.ToString(`yyyy`)). All rights reserved.</Copyright>
    <Authors>$(Company);Nikita Petko</Authors>

    <Version>$([System.DateTime]::Now.ToString(`yyyy.MM.dd+HHmmss`))</Version>

    <RepositoryUrl>https://github.com/mfdlabs/grid-bot-libraries</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup Label="TestsProperties" Condition="$(MSBuildProjectName.Contains('.Tests'))">
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Label="RootDirectory">
    <RootDirectory>$(MSBuildThisFileDirectory)../</RootDirectory>
  </PropertyGroup>

  <PropertyGroup Label="PackageProperties" Condition="'$(IsTestProject)' != 'true'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
    <DebugSymbols>true</DebugSymbols>
    <EmbedAllSources>true</EmbedAllSources>
    <DebugType>portable</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup Label="TestReferences" Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="NUnit" Version="4.1.0" />
	  <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />

    <Using Include="NUnit.Framework" />
  </ItemGroup>


  <!-- License -->
  <PropertyGroup>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(RootDirectory)LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
