<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Shared library for core interaction with grid server processes!</Description>
    <RootNamespace>Grid.ProcessManagement.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Grid.ProcessManagement.Docker</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.9.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\logging\logging\Logging.csproj" />
    <ProjectReference Include="..\..\random\random\Random.csproj" />
    <ProjectReference Include="..\..\clients\client-settings-client\ClientSettings.Client.csproj" />
    
    <ProjectReference Include="..\client\Grid.Client.csproj" />
    <ProjectReference Include="..\diagnostics\Grid.Diagnostics.csproj" />
    <ProjectReference Include="..\port-management\Grid.PortManagement.csproj" />
    <ProjectReference Include="..\commands\Grid.Commands.csproj" />
  </ItemGroup>
</Project>
