<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Shared utility classes used by the grid-bot</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);WE_LOVE_EM_SLASH_COMMANDS</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup Label="GridBotPackages">
    <ProjectReference Include="../settings/Grid.Bot.Settings.csproj" />
  </ItemGroup>

  <ItemGroup Label="CustomPackages">
    <ProjectReference Include="$(RootDirectory)lib/grid/job-management/Grid.JobManagement.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/logging/logging/Logging.csproj" />
  </ItemGroup>
  
  <ItemGroup Label="NuGetPackages">
    <PackageReference Include="Backtrace" Version="2.1.9" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="5.0.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.9.0" />
    <PackageReference Include="Discord.Net.WebSocket" Version="3.17.4" />
    <PackageReference Include="Discord.Net.Commands" Version="3.17.4" />
  </ItemGroup>
</Project>
