<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Shared utility classes used by the grid-bot</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);WE_LOVE_EM_SLASH_COMMANDS</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup Label="GridBotPackages">
    <ProjectReference Include="../settings/Shared.Settings.csproj" />
  </ItemGroup>

  <ItemGroup Label="CustomPackages">
    <ProjectReference Include="$(RootDirectory)lib/file-system/file-system/FileSystem.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/floodcheckers/core/FloodCheckers.Core.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/floodcheckers/redis/FloodCheckers.Redis.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/grid/commands/Grid.Commands.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/grid/client/Grid.Client.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/logging/logging/Logging.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/redis/redis/Redis.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/service-discovery/service-discovery/ServiceDiscovery.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/threading/threading/Threading.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/clients/users-client/Users.Client.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/grid/process-management-docker/Grid.ProcessManagement.Docker.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/grid/process-management-core/Grid.ProcessManagement.Core.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/networking/networking/Networking.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/clients/thumbnails-client/Thumbnails.Client.csproj" />
  </ItemGroup>
  
  <ItemGroup Label="NuGetPackages">
    <PackageReference Include="Backtrace" Version="2.1.9" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="5.0.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.9.0" />
    <PackageReference Include="Discord.Net.WebSocket" Version="3.17.4" />
    <PackageReference Include="Discord.Net.Commands" Version="3.17.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Lua/LuaVMTemplate.lua" />
    <None Remove="Lua/LuaVMTemplate.lua" />
  </ItemGroup>
</Project>
