<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Shared library containing settings used by the grid-bot</Description>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);DEBUG_LOGGING_IN_PROD</DefineConstants>
  </PropertyGroup>

  <ItemGroup Label="CustomPackages">
    <ProjectReference Include="$(RootDirectory)lib/configuration/configuration/Configuration.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/redis/redis/Redis.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/service-discovery/service-discovery/ServiceDiscovery.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/floodcheckers/redis/FloodCheckers.Redis.csproj" />

    <ProjectReference Include="$(RootDirectory)lib/grid/process-management-docker/Grid.ProcessManagement.Docker.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/grid/process-management-core/Grid.ProcessManagement.Core.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/grid/process-management/Grid.ProcessManagement.csproj" />

    <ProjectReference Include="$(RootDirectory)lib/clients/thumbnails-client/Thumbnails.Client.csproj" />
  </ItemGroup>

  <ItemGroup Label="NuGetPackages">
    <PackageReference Include="Discord.Net.Core" Version="3.17.4" />
    <PackageReference Include="Discord.Net.WebSocket" Version="3.17.4" />
    
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0" />
  </ItemGroup>

</Project>
