//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFDLabs.Concurrency.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class ConcurrencySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConcurrencySettings defaultInstance = ((ConcurrencySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConcurrencySettings())));
        
        public static ConcurrencySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrimaryDispatcherThreadCount {
            get {
                return ((int)(this["PrimaryDispatcherThreadCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MFDLabs Concurrency Service")]
        public string PrimaryDispatcherThreadPoolName {
            get {
                return ((string)(this["PrimaryDispatcherThreadPoolName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Threading.ThreadPriority PrimaryDispatcherThreadPriority {
            get {
                return ((global::System.Threading.ThreadPriority)(this["PrimaryDispatcherThreadPriority"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MFDLabs Concurrency Service")]
        public string PrimaryDispatcherQueueName {
            get {
                return ((string)(this["PrimaryDispatcherQueueName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UseBackgroundThreads")]
        public global::Microsoft.Ccr.Core.DispatcherOptions PrimaryDispatcherOptions {
            get {
                return ((global::Microsoft.Ccr.Core.DispatcherOptions)(this["PrimaryDispatcherOptions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsePerfmon {
            get {
                return ((bool)(this["UsePerfmon"]));
            }
        }
    }
}
