<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Shared utility classes related to client-settings</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  
  <ItemGroup Label="GridBotPackages">
    <ProjectReference Include="../settings/Grid.Bot.Settings.csproj" />
  </ItemGroup>

  <ItemGroup Label="CustomPackages">
    <ProjectReference Include="$(RootDirectory)lib/logging/logging/Logging.csproj" />
    <ProjectReference Include="$(RootDirectory)lib/clients/client-settings-client/ClientSettings.Client.csproj" />
  </ItemGroup>

  <ItemGroup Label="NuGetPackages">
    <PackageReference Include="VaultSharp" Version="1.13.0.1" />
    <PackageReference Include="prometheus-net" Version="8.0.1" />
  </ItemGroup>
</Project>
