<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://roblox.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://roblox.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://roblox.com/">
      <xs:element name="HelloWorld">
        <xs:complexType />
      </xs:element>
      <xs:element name="HelloWorldResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="1" name="HelloWorldResult" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetVersion">
        <xs:complexType />
      </xs:element>
      <xs:element name="GetVersionResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="GetVersionResult" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetStatus">
        <xs:complexType />
      </xs:element>
      <xs:element name="GetStatusResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="GetStatusResult" type="tns:Status" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:complexType name="Status">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="version" type="xs:string" />
          <xs:element minOccurs="1" maxOccurs="1" name="environmentCount" type="xs:int" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="OpenJob">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="job" type="tns:Job" />
            <xs:element minOccurs="0" maxOccurs="1" name="script" type="tns:ScriptExecution" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="OpenJobEx">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="job" type="tns:Job" />
            <xs:element minOccurs="0" maxOccurs="1" name="script" type="tns:ScriptExecution" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:complexType name="Job">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="id" type="xs:string" />
          <xs:element minOccurs="1" maxOccurs="1" name="expirationInSeconds" type="xs:double" />
          <xs:element minOccurs="1" maxOccurs="1" name="category" type="xs:int" />
          <xs:element minOccurs="1" maxOccurs="1" name="cores" type="xs:double" />
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="ScriptExecution">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="name" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="script" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="arguments" type="tns:ArrayOfLuaValue" />
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="ArrayOfLuaValue">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="LuaValue" nillable="true" type="tns:LuaValue" />
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="ArrayOfJob">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="Job" nillable="true" type="tns:Job" />
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="LuaValue">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="type" type="tns:LuaType" />
          <xs:element minOccurs="0" maxOccurs="1" name="value" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="table" type="tns:ArrayOfLuaValue" />
        </xs:sequence>
      </xs:complexType>
      <xs:simpleType name="LuaType">
        <xs:restriction base="xs:string">
          <xs:enumeration value="LUA_TNIL" />
          <xs:enumeration value="LUA_TBOOLEAN" />
          <xs:enumeration value="LUA_TNUMBER" />
          <xs:enumeration value="LUA_TSTRING" />
          <xs:enumeration value="LUA_TTABLE" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="OpenJobResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="OpenJobResult" type="tns:LuaValue"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="OpenJobExResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="OpenJobExResult" type="tns:ArrayOfLuaValue"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="RenewLease">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="jobID" type="xs:string" />
            <xs:element minOccurs="1" maxOccurs="1" name="expirationInSeconds" type="xs:double" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="RenewLeaseResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="RenewLeaseResult" type="xs:double" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Execute">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="jobID" type="xs:string" />
            <xs:element minOccurs="1" maxOccurs="1" name="script" type="tns:ScriptExecution" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ExecuteResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="ExecuteResult" nillable="true" type="tns:LuaValue" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ExecuteEx">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="jobID" type="xs:string" />
            <xs:element minOccurs="1" maxOccurs="1" name="script" type="tns:ScriptExecution" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ExecuteExResponse">
        <xs:complexType>
          <xs:sequence>
              <xs:element name="ExecuteExResult" type="tns:ArrayOfLuaValue"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CloseJob">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="jobID" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CloseJobResponse">
        <xs:complexType />
      </xs:element>
      <xs:element name="BatchJob">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="job" type="tns:Job" />
            <xs:element minOccurs="1" maxOccurs="1" name="script" type="tns:ScriptExecution" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="BatchJobResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="BatchJobResult" nillable="true" type="tns:LuaValue" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="BatchJobEx">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="job" type="tns:Job" />
            <xs:element minOccurs="1" maxOccurs="1" name="script" type="tns:ScriptExecution" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="BatchJobExResponse">
        <xs:complexType>
          <xs:sequence>
              <xs:element name="BatchJobExResult" type="tns:ArrayOfLuaValue"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetExpiration">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="jobID" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetExpirationResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="GetExpirationResult" type="xs:double" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetAllJobs">
        <xs:complexType />
      </xs:element>
      <xs:element name="GetAllJobsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="GetAllJobsResult" nillable="true" type="tns:Job" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetAllJobsEx">
        <xs:complexType />
      </xs:element>
      <xs:element name="GetAllJobsExResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="GetAllJobsExResult" type="tns:ArrayOfJob" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CloseExpiredJobs">
        <xs:complexType />
      </xs:element>
      <xs:element name="CloseExpiredJobsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="CloseExpiredJobsResult" type="xs:int" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CloseAllJobs">
        <xs:complexType />
      </xs:element>
      <xs:element name="CloseAllJobsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="CloseAllJobsResult" type="xs:int" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Diag">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="type" type="xs:int" />
            <xs:element minOccurs="0" maxOccurs="1" name="jobID" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DiagResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="DiagResult" nillable="true" type="tns:LuaValue" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DiagEx">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="type" type="xs:int" />
            <xs:element minOccurs="0" maxOccurs="1" name="jobID" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DiagExResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DiagExResult" type="tns:ArrayOfLuaValue" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
  </types>
  <message name="HelloWorldSoapIn">
    <part name="parameters" element="tns:HelloWorld" />
  </message>
  <message name="HelloWorldSoapOut">
    <part name="parameters" element="tns:HelloWorldResponse" />
  </message>
  <message name="GetVersionSoapIn">
    <part name="parameters" element="tns:GetVersion" />
  </message>
  <message name="GetVersionSoapOut">
    <part name="parameters" element="tns:GetVersionResponse" />
  </message>
  <message name="GetStatusSoapIn">
    <part name="parameters" element="tns:GetStatus" />
  </message>
  <message name="GetStatusSoapOut">
    <part name="parameters" element="tns:GetStatusResponse" />
  </message>
  <message name="OpenJobSoapIn">
    <part name="parameters" element="tns:OpenJob" />
  </message>
  <message name="OpenJobSoapOut">
    <part name="parameters" element="tns:OpenJobResponse" />
  </message>
  <message name="OpenJobExSoapIn">
    <part name="parameters" element="tns:OpenJobEx" />
  </message>
  <message name="OpenJobExSoapOut">
    <part name="parameters" element="tns:OpenJobExResponse" />
  </message>
  <message name="RenewLeaseSoapIn">
    <part name="parameters" element="tns:RenewLease" />
  </message>
  <message name="RenewLeaseSoapOut">
    <part name="parameters" element="tns:RenewLeaseResponse" />
  </message>
  <message name="ExecuteSoapIn">
    <part name="parameters" element="tns:Execute" />
  </message>
  <message name="ExecuteSoapOut">
    <part name="parameters" element="tns:ExecuteResponse" />
  </message>
  <message name="ExecuteExSoapIn">
    <part name="parameters" element="tns:ExecuteEx" />
  </message>
  <message name="ExecuteExSoapOut">
    <part name="parameters" element="tns:ExecuteExResponse" />
  </message>
  <message name="CloseJobSoapIn">
    <part name="parameters" element="tns:CloseJob" />
  </message>
  <message name="CloseJobSoapOut">
    <part name="parameters" element="tns:CloseJobResponse" />
  </message>
  <message name="BatchJobSoapIn">
    <part name="parameters" element="tns:BatchJob" />
  </message>
  <message name="BatchJobSoapOut">
    <part name="parameters" element="tns:BatchJobResponse" />
  </message>
  <message name="BatchJobExSoapIn">
    <part name="parameters" element="tns:BatchJobEx" />
  </message>
  <message name="BatchJobExSoapOut">
    <part name="parameters" element="tns:BatchJobExResponse" />
  </message>
  <message name="GetExpirationSoapIn">
    <part name="parameters" element="tns:GetExpiration" />
  </message>
  <message name="GetExpirationSoapOut">
    <part name="parameters" element="tns:GetExpirationResponse" />
  </message>
  <message name="GetAllJobsSoapIn">
    <part name="parameters" element="tns:GetAllJobs" />
  </message>
  <message name="GetAllJobsSoapOut">
    <part name="parameters" element="tns:GetAllJobsResponse" />
  </message>
  <message name="GetAllJobsExSoapIn">
    <part name="parameters" element="tns:GetAllJobsEx" />
  </message>
  <message name="GetAllJobsExSoapOut">
    <part name="parameters" element="tns:GetAllJobsExResponse" />
  </message>
  <message name="CloseExpiredJobsSoapIn">
    <part name="parameters" element="tns:CloseExpiredJobs" />
  </message>
  <message name="CloseExpiredJobsSoapOut">
    <part name="parameters" element="tns:CloseExpiredJobsResponse" />
  </message>
  <message name="CloseAllJobsSoapIn">
    <part name="parameters" element="tns:CloseAllJobs" />
  </message>
  <message name="CloseAllJobsSoapOut">
    <part name="parameters" element="tns:CloseAllJobsResponse" />
  </message>
  <message name="DiagSoapIn">
    <part name="parameters" element="tns:Diag" />
  </message>
  <message name="DiagSoapOut">
    <part name="parameters" element="tns:DiagResponse" />
  </message>
  <message name="DiagExSoapIn">
    <part name="parameters" element="tns:DiagEx" />
  </message>
  <message name="DiagExSoapOut">
    <part name="parameters" element="tns:DiagExResponse" />
  </message>
  <portType name="RCCServiceSoap">
    <operation name="HelloWorld">
      <input message="tns:HelloWorldSoapIn" />
      <output message="tns:HelloWorldSoapOut" />
    </operation>
    <operation name="GetVersion">
      <input message="tns:GetVersionSoapIn" />
      <output message="tns:GetVersionSoapOut" />
    </operation>
    <operation name="GetStatus">
      <input message="tns:GetStatusSoapIn" />
      <output message="tns:GetStatusSoapOut" />
    </operation>
    <operation name="OpenJob">
      <input message="tns:OpenJobSoapIn" />
      <output message="tns:OpenJobSoapOut" />
    </operation>
    <operation name="OpenJobEx">
      <input message="tns:OpenJobExSoapIn" />
      <output message="tns:OpenJobExSoapOut" />
    </operation>
    <operation name="RenewLease">
      <input message="tns:RenewLeaseSoapIn" />
      <output message="tns:RenewLeaseSoapOut" />
    </operation>
    <operation name="Execute">
      <input message="tns:ExecuteSoapIn" />
      <output message="tns:ExecuteSoapOut" />
    </operation>
    <operation name="ExecuteEx">
      <input message="tns:ExecuteExSoapIn" />
      <output message="tns:ExecuteExSoapOut" />
    </operation>
    <operation name="CloseJob">
      <input message="tns:CloseJobSoapIn" />
      <output message="tns:CloseJobSoapOut" />
    </operation>
    <operation name="BatchJob">
      <input message="tns:BatchJobSoapIn" />
      <output message="tns:BatchJobSoapOut" />
    </operation>
    <operation name="BatchJobEx">
      <input message="tns:BatchJobExSoapIn" />
      <output message="tns:BatchJobExSoapOut" />
    </operation>
    <operation name="GetExpiration">
      <input message="tns:GetExpirationSoapIn" />
      <output message="tns:GetExpirationSoapOut" />
    </operation>
    <operation name="GetAllJobs">
      <input message="tns:GetAllJobsSoapIn" />
      <output message="tns:GetAllJobsSoapOut" />
    </operation>
    <operation name="GetAllJobsEx">
      <input message="tns:GetAllJobsExSoapIn" />
      <output message="tns:GetAllJobsExSoapOut" />
    </operation>
    <operation name="CloseExpiredJobs">
      <input message="tns:CloseExpiredJobsSoapIn" />
      <output message="tns:CloseExpiredJobsSoapOut" />
    </operation>
    <operation name="CloseAllJobs">
      <input message="tns:CloseAllJobsSoapIn" />
      <output message="tns:CloseAllJobsSoapOut" />
    </operation>
    <operation name="Diag">
      <input message="tns:DiagSoapIn" />
      <output message="tns:DiagSoapOut" />
    </operation>
    <operation name="DiagEx">
      <input message="tns:DiagExSoapIn" />
      <output message="tns:DiagExSoapOut" />
    </operation>
  </portType>
  <binding name="RCCServiceSoap" type="tns:RCCServiceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="HelloWorld">
      <soap:operation soapAction="http://roblox.com/HelloWorld" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="GetVersion">
      <soap:operation soapAction="http://roblox.com/GetVersion" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="GetStatus">
      <soap:operation soapAction="http://roblox.com/GetStatus" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="OpenJob">
      <soap:operation soapAction="http://roblox.com/OpenJob" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="OpenJobEx">
      <soap:operation soapAction="http://roblox.com/OpenJobEx" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="RenewLease">
      <soap:operation soapAction="http://roblox.com/RenewLease" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="Execute">
      <soap:operation soapAction="http://roblox.com/Execute" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="ExecuteEx">
      <soap:operation soapAction="http://roblox.com/ExecuteEx" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="CloseJob">
      <soap:operation soapAction="http://roblox.com/CloseJob" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="BatchJob">
      <soap:operation soapAction="http://roblox.com/BatchJob" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="BatchJobEx">
      <soap:operation soapAction="http://roblox.com/BatchJobEx" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="GetExpiration">
      <soap:operation soapAction="http://roblox.com/GetExpiration" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="GetAllJobs">
      <soap:operation soapAction="http://roblox.com/GetAllJobs" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="GetAllJobsEx">
      <soap:operation soapAction="http://roblox.com/GetAllJobsEx" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="CloseExpiredJobs">
      <soap:operation soapAction="http://roblox.com/CloseExpiredJobs" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="CloseAllJobs">
      <soap:operation soapAction="http://roblox.com/CloseAllJobs" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="Diag">
      <soap:operation soapAction="http://roblox.com/Diag" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="DiagEx">
      <soap:operation soapAction="http://roblox.com/DiagEx" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <binding name="RCCServiceSoap12" type="tns:RCCServiceSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="HelloWorld">
      <soap12:operation soapAction="http://roblox.com/HelloWorld" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="GetVersion">
      <soap12:operation soapAction="http://roblox.com/GetVersion" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="GetStatus">
      <soap12:operation soapAction="http://roblox.com/GetStatus" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="OpenJob">
      <soap12:operation soapAction="http://roblox.com/OpenJob" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="OpenJobEx">
      <soap12:operation soapAction="http://roblox.com/OpenJobEx" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="RenewLease">
      <soap12:operation soapAction="http://roblox.com/RenewLease" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="Execute">
      <soap12:operation soapAction="http://roblox.com/Execute" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="ExecuteEx">
      <soap12:operation soapAction="http://roblox.com/ExecuteEx" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="CloseJob">
      <soap12:operation soapAction="http://roblox.com/CloseJob" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="BatchJob">
      <soap12:operation soapAction="http://roblox.com/BatchJob" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="BatchJobEx">
      <soap12:operation soapAction="http://roblox.com/BatchJobEx" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="GetExpiration">
      <soap12:operation soapAction="http://roblox.com/GetExpiration" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="GetAllJobs">
      <soap12:operation soapAction="http://roblox.com/GetAllJobs" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="GetAllJobsEx">
      <soap12:operation soapAction="http://roblox.com/GetAllJobsEx" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="CloseExpiredJobs">
      <soap12:operation soapAction="http://roblox.com/CloseExpiredJobs" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="CloseAllJobs">
      <soap12:operation soapAction="http://roblox.com/CloseAllJobs" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="Diag">
      <soap12:operation soapAction="http://roblox.com/Diag" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    <operation name="DiagEx">
      <soap12:operation soapAction="http://roblox.com/DiagEx" style="document" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="RCCServiceSoap">
    <port name="RCCServiceSoapPort" binding="tns:RCCServiceSoap">
      <soap:address location="127.0.0.1:64989"/>
    </port>
  </service>
</definitions>
