//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class HybridRedisClientProviderSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HybridRedisClientProviderSettings defaultInstance = ((HybridRedisClientProviderSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HybridRedisClientProviderSettings())));
        
        public static HybridRedisClientProviderSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan InitialDiscoveryWaitTime {
            get {
                return ((global::System.TimeSpan)(this["InitialDiscoveryWaitTime"]));
            }
        }
    }
}
