name: Compile Source Code

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.103
      - name: Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - run: nuget restore MFDLabs.Grid.sln
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build --verbosity normal
